apiVersion: v1
kind: Template
metadata:
  name: ace-configuration-with-secret
objects:
- apiVersion: appconnect.ibm.com/v1beta1
  kind: Configuration
  metadata:
    name: ${NAME}
    labels:
      app.kubernetes.io/instance: ${RELEASE_NAME}
  spec:
    type: ${TYPE}
    secretName: ${SECRET_NAME}
parameters:
- description: Name of the Configuration
  name: NAME
- description: Type of Configuration
  name: TYPE
- description: Secret that contains the data that this configuration refers to
  name: SECRET_NAME
- description: Name of the release for which this object was created
  name: RELEASE_NAME
